# work flow to convert dsupdt.usg in repo rda_python_dsupdt into docs/source/sections*.rst
on:
  repository_dispatch:
    types: [trigger-conversion]

jobs:
  convert_file:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout Repo gdex_docs_dsupdt
        uses: actions/checkout@v6
        with:
          ref: main

      - name: Checkout Repo rda_python_dsupdt
        uses: actions/checkout@v6
        with:
          repository: NCAR/rda-python-dsupdt
          path: dsupdt
          # Use the branch passed in the payload, defaulting to 'main' if not provided
          ref: ${{ github.event.client_payload.branch || 'main' }}
      
      - name: Convert dsupdt.usg
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pgrst -d ${{ github.workspace }}/docs/source -u dsupdt/src/rda_python_dsupdt/dsupdt.usg -p dsupdt/src/rda_python_dsupdt/pg_updt.py

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v8
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "docs: update automated files"
          branch: "automated-update-branch" # Local branch name
          base: "main"                      # Target branch
          title: "Automated File Update"
          body: "This PR was automatically generated by GitHub Actions."
          delete-branch: true # Ensures the action cleans up if the PR becomes unnecessary
